services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./database/postgres:/var/lib/postgresql/data/pgdata
      - ./database/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo:
    image: mongo:8
    volumes:
      - ./database/mongo:/data/db/mongodata
    ports:
      - "27017:27017"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./api:/app
    env_file: .env
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "extractor", "worker", "--loglevel=info"]

    working_dir: /app
    volumes:
      - ./api:/app
    env_file: .env
    depends_on:
      - redis
      - mongo
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"


  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "extractor", "beat", "--loglevel=info"]
    volumes:
      - ./api:/app
    env_file: .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  nlp-gateway:
    build:
      context: .
      dockerfile: ./nlp-gateway/Dockerfile
    env_file: .env
    volumes:
      - ./nlp-gateway:/app    
    ports:
      - "8100:8100"
    environment:
      OLLAMA_HOST: http://localhost:11434
      OLLAMA_MODEL: phi3:3.8b
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: ./database/redis/Dockerfile
    volumes:
    - ./api:/app
    working_dir: /app
    command:
      - celery
      - -A
      - task
      - flower
      - --port=5555

    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped

volumes:
  pgdata:
  mongodata:
  miniodata:
