# Generated by Django 5.2.8 on 2026-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrapper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapersource",
            name="content_selector",
            field=models.CharField(
                blank=True,
                help_text="Seletor CSS para conteúdo (ex: div.content)",
                max_length=200,
                null=True,
                verbose_name="Seletor de Conteúdo",
            ),
        ),
        migrations.AlterField(
            model_name="scrapersource",
            name="title_selector",
            field=models.CharField(
                blank=True,
                help_text="Seletor CSS para título (ex: h1.title)",
                max_length=200,
                null=True,
                verbose_name="Seletor de Título",
            ),
        ),
    ]
